### ISSUE TITLE
/sbin/module.prop: No such file or directory

### ISSUE THREAD

**Issue by CodeNameT1M** [piyushgarg/rclone-mount#4]
OS: Android 9, May Security Patch
Device: Redmi note 4x (mido)
Installed Magisk Version/Manager: 19.4-1058aeb0/7.3.3-f1112fdf
Installed Module Version: 1.3

![grafik](https://user-images.githubusercontent.com/28508724/60587672-5697fd00-9d95-11e9-9fe0-6f75a60ccad4.png)

Issue:
After installing the Module and placing a rclone.conf in /storage/emulated/0/.rclone/ i'll get the following error: 
/sbin/rclone-mount[10]: .: /sbin/module.prop: No such file or directory

![grafik](https://user-images.githubusercontent.com/28508724/60587796-9fe84c80-9d95-11e9-85fc-122ed1058130.png)

![grafik](https://user-images.githubusercontent.com/28508724/60587818-af679580-9d95-11e9-8582-a74c141348db.png)

Is it just my device or a problem which can be easily fixed?
- CodeNameT1M

**Comment by piyushgarg** [comment]
You should be able to see the mount points on device restart after 5 minutes. I will fix this error.
Use adb shell and probably try changing the directory to /data/adb/modules/com.piyushgarg.rclone before executing the rclone-mount.
rclone-mount is the manual way to mount directories. 
It is an initial module so it would take 2 - 3 iterations to be smoother.

**Comment by piyushgarg** [comment]
as I can see here you should be able to see the mount points after restart.
/mnt/cloud or (linked location /storage/cloud)

**Comment by piyushgarg** [comment]
Let me know if it still does not work for you.

**Comment by CodeNameT1M** [comment]
![grafik](https://user-images.githubusercontent.com/28508724/60598169-81da1680-9dac-11e9-9222-7f1ac8c2a100.png)

![grafik](https://user-images.githubusercontent.com/28508724/60598265-ae8e2e00-9dac-11e9-9e18-5efa034317fa.png)


The mount point works and is accessible from any app, thanks!

Maybe add the Information in the README? Many people might thought that you need to mount it with rclone-mount manually to set it up

**Comment by CodeNameT1M** [comment]
EDIT: you can mark this Issue as "solved"
